<?php

namespace nikserg\NepApi;

use GuzzleHttp\RequestOptions;

class PartialClient extends Client
{
    private $additionalQuery;

    public function __construct(
        string $modelClassName,
        int $modelId,
        string $token,
        protected string $host = 'https://crm.uc-itcom.ru',
    ) {
        $this->additionalQuery = [
            'modelId'    => $modelId,
            'modelClass' => $modelClassName,
            'token'      => $token,
        ];
        $this->client = new \GuzzleHttp\Client([
            'base_uri'                  => $this->host,
            RequestOptions::VERIFY      => false,
            RequestOptions::HTTP_ERRORS => false,
        ]);
    }

    public function doMethod(string $method, string $action, $options): array
    {
        $queryParams = $options[RequestOptions::QUERY] ?? [];
        $queryParams += $this->additionalQuery;
        $options[RequestOptions::QUERY] = $queryParams;

        return parent::doMethod($method, $action, $options); // TODO: Change the autogenerated stub
    }
}